name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v3
    secrets:
      halo-username: ${{ secrets.HALO_USERNAME }}
      halo-password: ${{ secrets.HALO_PASSWORD }}
    permissions:
      contents: write
    with:
      pnpm-version: "10"
      app-id: app-kqZUw
      skip-node-setup: false
      ui-path: "ui"
